# Generated by Django 2.2.12 on 2022-11-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20221101_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('nama', models.CharField(max_length=20)),
                ('jenispembelian', models.CharField(max_length=20)),
                ('tglbeli', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datapenjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('produk', models.CharField(max_length=20)),
                ('kategori', models.CharField(max_length=15)),
                ('merk', models.CharField(max_length=20)),
                ('totalunit', models.IntegerField()),
                ('totalpenjualan', models.BigIntegerField()),
            ],
        ),
    ]
